[package]
name = "wdu-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true }
wdu-config = { workspace = true }
wdu-core = { workspace = true }
wdu-usage = { workspace = true }
wdu-storage = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
notify = { workspace = true }
